import cs3500.animator.create.BSTAnimation;
import cs3500.animator.create.BubbleSort;
import java.io.FileWriter;
import java.io.IOException;

/**
 * main class for auto generating an animation. the choices are a BSTAnimation or a BubbleSort
 * animation.
 */
public class MakeAutoGeneratedAnimation {

  /**
   * main method to kick off the program from the command line.
   *
   * @param args command line arguments bubble {int} {outputFile} - makes a BubbleSort animation
   *             with int bars and writes it to the outputFile bst {int} {outputFile} - makes a
   *             BSTAnimation animation with int nodes and writes it to the outputFile
   */
  public static void main(String[] args) throws IOException {
    String animationType = args[0];
    int amount = Integer.parseInt(args[1]);
    String outFile = args[2];

    FileWriter out = new FileWriter(outFile);

    if (animationType.equals("bubble")) {
      new BubbleSort(amount).makeAnimation(out);
    } else if (animationType.equals("bst")) {
      new BSTAnimation(amount).makeAnimation(out);
    } else {
      throw new IllegalArgumentException("Bad command");
    }

    out.flush();
    out.close();

  }
}
